server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.77.254:7708/guli_ums
    username: root
    password: 1997
  redis:
    host: 101.37.77.254
    port: 7777
    password: Cai19970709
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:mapper/ums/**/*.xml
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    com.atguigu.gmall: debug